name: zip

# Controls when the workflow will run
on:
  release:
    types: [ "created" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make .zip file
        run: zip -r ../Fluffcord-Minecraft.zip ./*

      - name: Upload Zip File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../Fluffcord-Minecraft.zip
          asset_name: Fluffcord-Minecraft.zip
          asset_content_type: application/zip
